AllCops:
  Excludes:
    - vendor/**

HashSyntax:
  EnforcedStyle: hash_rockets

Encoding:
  Enabled: false

Blocks:
  Enabled: false

LineLength:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

Documentation:
  Enabled: false

MethodLength:
  CountComments: false
  Max: 20

IfUnlessModifier:
  Enabled: false


ParameterLists:
  Enabled: false

ClassLength:
  Max: 200

SingleLineBlockParams:
  Methods: []
