---
# BOSH NATS settings
nats: &nats
  uri: mbus://192.168.50.4:21084
  user: nats
  pass: nats

# BOSH Director REST API settings
rest: &rest
  endpoint_uri: https://192.168.50.4:25555
  user: scaler
  password: scaler
  disable_verify_certification: true

collectors:
  - class: BoshNatsCollector
    bosh_nats: *nats
    bosh_rest: *rest
  - class: CfVarzTsdbCollector # Optional for CF
    port: 4567

listeners:
  - class: BoshScaler
    bosh_rest: *rest
    interval: 60 # seconds
    buffer_size: 1000
    ui:
      enable: true
      port: 8888