---
name: test
director_uuid: test-uuid

resource_pools:
  - name: pool0
    size: 3
  - name: pool1 # with standby
    size: 4
  - name: pool2
    size: 9999

jobs:
  - name: job0a
    instances: 1
    resource_pool: pool0
  - name: job0b
    instances: 2
    resource_pool: pool0
  - name: job1a
    instances: 2
    resource_pool: pool1
  - name: job2a
    instances: 2
    resource_pool: pool2
    networks:
      - name: net00
        static_ips:
          - 10.39.3.9
          - 10.39.3.10
scale:
  jobs:
    - name: job0a
      cooldown: 39
      out:
        limit: 9
        unit: 3
        conditions:
          - class: dummy_out0a
            additional: value_out0a
      in:
        limit: 3
        unit: 2
        conditions:
          - class: dummy_in0a
            additional: value_in0a
    - name: job0b
      cooldown: 702
      out:
        limit: 70
        conditions:
          - class: dummy_out0b
            additional: value_out0b
      in:
        limit: 2
        conditions:
          - class: dummy_in0b
            additional: value_in0b
  networks:
    - name: net00
      static_ips:
        - 10.39.3.100
        - 10.39.3.101
    - name: net01
