---
logging:
  level: debug
  file: /dev/null

nats: &nats
  uri: mbus://10.1.1.39:4222
  user: nats
  pass: nats

rest: &rest
  endpoint_uri: https://10.1.1.39:25555
  user: admin
  password: admin
  disable_verify_certification: true

collectors:
  - class: BoshNatsCollector
    bosh_nats: *nats
    bosh_rest: *rest
  - class: CfVarzCollector
    port: 4567

listeners:
  - class: BoshScaler
    bosh_rest: *rest
    interval: 60
    buffer_size: 1000
    rules:
      - deployment: cf
        job: router
        cooldown: 300
        out:
          limit: 10
          condition:
            class: CpuAverage
            larger_than: 80
            duration: 300
        in:
          limit: 2
          condition:
            class: CpuAverage
            smaller_than: 10
            duration: 300
