---
name: test1
director_uuid: test-uuid

resource_pools:
  - name: pool0
    size: 1000000

jobs:
  - name: go0o
    instances: 1
    resource_pool: pool0
  - name: go0i
    instances: 10000
    resource_pool: pool0
  - name: stop0o
    instances: 10000
    resource_pool: pool0
  - name: stop0i
    instances: 1
    resource_pool: pool0

  - name: go1o
    instances: 1
    resource_pool: pool0
  - name: go1i
    instances: 10000
    resource_pool: pool0
  - name: stop1o
    instances: 10000
    resource_pool: pool0
  - name: stop1i
    instances: 1
    resource_pool: pool0

scale:
  jobs:
    - name: go0o
      cooldown: 39
      out:
        limit: 39
        conditions:
          - class: CpuAverage
            larger_than: 80
          - class: MemoryAverage
            larger_than: 70
      in:
        limit: 7
        conditions:
          - class: CpuAverage
            smaller_than: 10
    - name: go0i
      cooldown: 702
      out:
        limit: 101
        conditions:
          - class: MemoryAverage
            larger_than: 93
